#!/usr/bin/env python

from sys import argv
from math import log,tan,cos,pi,radians

lat_deg=float(argv[1])
zoom=int(argv[2])
n = 2.0 ** zoom
print "%d" % int((1.0 - log(tan(radians(lat_deg)) + (1 / cos(radians(lat_deg)))) / pi) / 2.0 * n)
