#!/usr/bin/env python

from sys import argv
from math import atan, sinh, pi, degrees

ytile=int(argv[1])
zoom=int(argv[2])
n = 2.0 ** zoom
print "%.7f" % (degrees(atan(sinh(pi * (1 - 2 * ytile / n)))))

