#!/usr/bin/env bash

FROM=( "/root/map1/map/tiles-cz/$1" "/root/map1/map/tiles-sk/$1" "/root/map1/map/tiles-at/$1" "/root/map1/map/tiles-pl/$1" "/root/map1/map/tiles-sl/$1" "/root/map1/map/tiles-hu/$1" "/root/map1/map/tiles-hr/$1"  )
TO="/root/map1/map/tiles/$1"

rm -rf $TO
mkdir $TO

for FR in "${FROM[@]}"; do
	./copy-tiles $FR $TO
done
