#!/usr/bin/env bash

createdb -E UTF8 -O klinger $1
createlang plpgsql $1
#psql -d $1 -f /usr/share/postgresql/8.4/contrib/_int.sql
psql -d $1 -f /usr/share/postgresql/8.4/contrib/postgis-2.0/postgis.sql
psql -d $1 -f /usr/share/postgresql/8.4/contrib/postgis-2.0/spatial_ref_sys.sql
psql $1 -c "ALTER TABLE geometry_columns OWNER TO klinger"
psql $1 -c "ALTER TABLE geography_columns OWNER TO klinger"
psql $1 -c "ALTER TABLE spatial_ref_sys OWNER TO klinger"
