#!/usr/bin/env bash

exists=$(ps -ef | grep "process\-queue" | wc -l)

if [ $exists -gt 2 ]; then	
	echo "already running"
	echo $exists
	exit
fi


while [ -s $1 ]; do
	$(head -n 1 $1)
	tail -n +2 $1 > /tmp/~$1
	mv /tmp/~$1 $1
done
