<!--Settings for Mapnik Fonts
To see the fonts you have installed with Mapnik do:
ls `python -c "import mapnik;print mapnik.fontscollectionpath"`-->

<FontSet name="book-fonts">
  <Font face-name="Liberation Sans Narrow Regular" />
  <Font face-name="unifont Medium" />
</FontSet>
<FontSet name="bold-fonts">
  <Font face-name="Liberation Sans Narrow Bold" />
  <Font face-name="unifont Medium" />
</FontSet>
<FontSet name="oblique-fonts">
  <Font face-name="Liberation Sans Narrow Italic" />
  <Font face-name="unifont Medium" />
</FontSet>
