<?php
require_once "inc/utils.php";
require_once "conf/common.conf.php";
require_once "conf/waters.conf.php";

$_SYMBOL_ATTRACTIVE_COLOR = array(12 => '#aa00aa');

$SYMBOL_DENSITY = array(11 => 5, 12 => 20,13 => 50, 14 => 200, 15 => 1000,16 => 20000);

$_SYMBOL_HALO_COLOR = array(12 => '#FFFAAA');


$_SYMBOL_TRANSPORT_COLOR = array(12 => '#071133');
$_SYMBOL_TRANSPORT_HALO_COLOR = array(12 => '#E4EEFF');
$_SYMBOL_TRANSPORT_HALO_OPACITY = array(12 => 0.4);

$_SYMBOL_HISTORIC_COLOR = array(12 => '#880000');
$_SYMBOL_HISTORIC_HALO_COLOR = $_SYMBOL_HALO_COLOR;

$_SYMBOL_AMENITY_COLOR = array(12 => '#555555');
$_SYMBOL_AMENITY_HALO_COLOR = array(12 => '#FFFFFF');

$_SYMBOL_SPORT_COLOR = array(12 => '#883300');
$_SYMBOL_SPORT_HALO_COLOR = array(12 => '#ffe3c0');

$_SYMBOL_SHOP_COLOR = array(12 => '#330022');
$_SYMBOL_SHOP_HALO_COLOR = array(12 => '#ffddf5');

$_SYMBOL_NATURAL_COLOR = array(12 => '#448800');
$_SYMBOL_NATURAL_HALO_COLOR = $_SYMBOL_HALO_COLOR;

$_SYMBOl_SIZE_HUGE   = array(11=>20,14=>34,18=>45);
$_SYMBOl_SIZE_BIG    = array(11=>15,14=>28,18=>35);
$_SYMBOl_SIZE_NORMAL = array(11=>11.5,14=>19,18=>23);
$_SYMBOl_SIZE_SMALL  = array(11=> 9,14=>14,18=>18);
$_SYMBOl_SIZE_TINY   = array(11=> 7,14=>11.5,18=>14);

$_SYMBOl_TEXT_SIZE_HUGE   = array(11=>15,15=>19,18=>23);
$_SYMBOl_TEXT_SIZE_BIG    = array(11=>12,15=>15,18=>18);
$_SYMBOl_TEXT_SIZE_NORMAL = array(11=> 9,15=>11.5,18=>14);
$_SYMBOl_TEXT_SIZE_SMALL  = array(11=> 7,15=> 9,18=>11);
$_SYMBOl_TEXT_SIZE_TINY   = array(11=> 5,15=> 7,18=> 9);

$_SYMBOl_ZOOMS_HUGE    = array(11 => 4, 12 => 3, 13 => 3, 14 => 2, 15 => 2, 16 => 1, 17 => 1, 18 => 1);
$_SYMBOl_ZOOMS_HUGELOW = array(11 => 4, 12 => 4, 13 => 3, 14 => 3, 15 => 2, 16 => 2, 17 => 1, 18 => 1);
$_SYMBOl_ZOOMS_BIG     = array(         12 => 4, 13 => 3, 14 => 3, 15 => 2, 16 => 2, 17 => 1, 18 => 1);
$_SYMBOl_ZOOMS_NORMAL  = array(                  13 => 4, 14 => 3, 15 => 3, 16 => 2, 17 => 2, 18 => 1);
$_SYMBOl_ZOOMS_SMALL   = array(                           14 => 4, 15 => 3, 16 => 3, 17 => 2, 18 => 2);
$_SYMBOl_ZOOMS_TINY    = array(                                    15 => 4, 16 => 4, 17 => 3, 18 => 2);

/**
 * Zoom x symbol look maping
 */
$SYMBOL = array(
	"[historic='castle'][castle_type='no'][ruins='no'],[historic='castle'][castle_type='stately'][ruins='no'],[historic='castle'][castle_type='schloss'][ruins='no'],[historic='castle'][castle_type='burg;schloss'][ruins='no']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_HUGE,
			'symbol-file'  => 'castle-stately',
			'symbol-size'  => $_SYMBOl_SIZE_HUGE,
			'text-size'    => $_SYMBOl_TEXT_SIZE_HUGE,
			'symbol-color' => $_SYMBOL_HISTORIC_COLOR,
			'text-color'   => $_SYMBOL_HISTORIC_COLOR,
			'symbol-halo'  => $_SYMBOL_HISTORIC_HALO_COLOR,
			'halo-color'   => $_SYMBOL_HISTORIC_HALO_COLOR,
		),	
	
	"[historic='castle'][castle_type='defensive'],[historic='castle'][castle_type='burg'],[historic='castle'][castle_type='fortress'],[historic='castle'][castle_type='festung']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_HUGE,
			'symbol-file'  => 'castle-defensive',
			'symbol-size'  => $_SYMBOl_SIZE_HUGE,
			'text-size'    => $_SYMBOl_TEXT_SIZE_HUGE,
			'symbol-color' => $_SYMBOL_HISTORIC_COLOR,
			'text-color'   => $_SYMBOL_HISTORIC_COLOR,
			'symbol-halo'  => $_SYMBOL_HISTORIC_HALO_COLOR,
			'halo-color'   => $_SYMBOL_HISTORIC_HALO_COLOR,
		),
	
		
	"[ruins!='no'][historic='castle'],[ruins='castle']" => array(			
			'zooms'        => $_SYMBOl_ZOOMS_HUGE,
			'symbol-file'  => 'ruins',
			'symbol-size'  => $_SYMBOl_SIZE_BIG,
			'text-size'    => $_SYMBOl_TEXT_SIZE_BIG,
			'symbol-color' => $_SYMBOL_HISTORIC_COLOR,
			'text-color'   => $_SYMBOL_HISTORIC_COLOR,
			'symbol-halo'  => $_SYMBOL_HISTORIC_HALO_COLOR,
			'halo-color'   => $_SYMBOL_HISTORIC_HALO_COLOR,
		),	
	
	"[building='church'],[amenity='place_of_worship'][historic!='monastery'][historic!='wayside_shrine'][historic!='wayside_cross'][building!='chapel'][\"place_of_worship:type\"!='chapel'][place_of_worship!='chapel'][\"place_of_worship:type\"!='monastery'][place_of_worship!='monastery']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_BIG,
			'symbol-file'  => 'church',
			'symbol-size'  => $_SYMBOl_SIZE_NORMAL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_NORMAL,
			'symbol-color' => $_SYMBOL_HISTORIC_COLOR,
			'text-color'   => $_SYMBOL_HISTORIC_COLOR,
			'symbol-halo'  => $_SYMBOL_HISTORIC_HALO_COLOR,
			'halo-color'   => $_SYMBOL_HISTORIC_HALO_COLOR,
		),	
		
	"[building='chapel'],[\"place_of_worship:type\"='chapel'],[place_of_worship='chapel']"=> array(			
			'zooms'        => $_SYMBOl_ZOOMS_NORMAL,
			'symbol-file'  => 'chapel',
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_SMALL,
			'symbol-color' => $_SYMBOL_HISTORIC_COLOR,
			'text-color'   => $_SYMBOL_HISTORIC_COLOR,
			'symbol-halo'  => $_SYMBOL_HISTORIC_HALO_COLOR,
			'halo-color'   => $_SYMBOL_HISTORIC_HALO_COLOR,
		),	
	"[military='bunker'][historic='yes']" => array(			
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,
			'symbol-file'  => 'military_bunker',
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-color' => $_SYMBOL_HISTORIC_COLOR,
			'text-color'   => $_SYMBOL_HISTORIC_COLOR,
			'symbol-halo'  => $_SYMBOL_HISTORIC_HALO_COLOR,
			'halo-color'   => $_SYMBOL_HISTORIC_HALO_COLOR,
		),	
	"[historic='monastery'],[\"place_of_worship:type\"='monastery'],[place_of_worship='monastery']"=> array(			
			'zooms'        => $_SYMBOl_ZOOMS_HUGE,
			'symbol-file'  => 'monastery',
			'symbol-size'  => $_SYMBOl_SIZE_BIG,
			'text-size'    => $_SYMBOl_TEXT_SIZE_BIG,
			'symbol-color' => $_SYMBOL_HISTORIC_COLOR,
			'text-color'   => $_SYMBOL_HISTORIC_COLOR,
			'symbol-halo'  => $_SYMBOL_HISTORIC_HALO_COLOR,
			'halo-color'   => $_SYMBOL_HISTORIC_HALO_COLOR,
		),		
	"[historic='archaeological_site']" => array(			
			'zooms'        => $_SYMBOl_ZOOMS_BIG,
			'symbol-file'  => 'archaeological_site',
			'symbol-size'  => $_SYMBOl_SIZE_NORMAL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_NORMAL,
			'symbol-color' => $_SYMBOL_HISTORIC_COLOR,
			'text-color'   => $_SYMBOL_HISTORIC_COLOR,
			'symbol-halo'  => $_SYMBOL_HISTORIC_HALO_COLOR,
			'halo-color'   => $_SYMBOL_HISTORIC_HALO_COLOR,
		),
	"[historic='city_gate']" => array(			
			'zooms'        => $_SYMBOl_ZOOMS_BIG,
			'symbol-file'  => 'city_gate',
			'symbol-size'  => $_SYMBOl_SIZE_NORMAL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_NORMAL,
			'symbol-color' => $_SYMBOL_HISTORIC_COLOR,
			'text-color'   => $_SYMBOL_HISTORIC_COLOR,
			'symbol-halo'  => $_SYMBOL_HISTORIC_HALO_COLOR,
			'halo-color'   => $_SYMBOL_HISTORIC_HALO_COLOR,
		),
	"[historic='monument']" => array(			
			'zooms'        => $_SYMBOl_ZOOMS_BIG,
			'symbol-file'  => 'monument',
			'symbol-size'  => $_SYMBOl_SIZE_NORMAL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_NORMAL,
			'symbol-color' => $_SYMBOL_HISTORIC_COLOR,
			'text-color'   => $_SYMBOL_HISTORIC_COLOR,
			'symbol-halo'  => $_SYMBOL_HISTORIC_HALO_COLOR,
			'halo-color'   => $_SYMBOL_HISTORIC_HALO_COLOR,
		),	
	"[historic='memorial'],[historic='heritage']" => array(			
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,
			'symbol-file'  => 'memorial',
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-color' => $_SYMBOL_HISTORIC_COLOR,
			'text-color'   => $_SYMBOL_HISTORIC_COLOR,
			'symbol-halo'  => $_SYMBOL_HISTORIC_HALO_COLOR,
			'halo-color'   => $_SYMBOL_HISTORIC_HALO_COLOR,
		),
	"[historic='wayside_cross'],[amenity='place_of_worship'][historic='no'][building='no']" => array(			
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,
			'symbol-file'  => 'waysidecross',
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-color' => $_SYMBOL_HISTORIC_COLOR,
			'text-color'   => $_SYMBOL_HISTORIC_COLOR,
			'symbol-halo'  => $_SYMBOL_HISTORIC_HALO_COLOR,
			'halo-color'   => $_SYMBOL_HISTORIC_HALO_COLOR,
		),
	"[historic='wayside_shrine']" => array(			
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,
			'symbol-file'  => 'waysideshrine',
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-color' => $_SYMBOL_HISTORIC_COLOR,
			'text-color'   => $_SYMBOL_HISTORIC_COLOR,
			'symbol-halo'  => $_SYMBOL_HISTORIC_HALO_COLOR,
			'halo-color'   => $_SYMBOL_HISTORIC_HALO_COLOR,
		),
	"[historic='boundary_stone']" => array(			
			'zooms'        => $_SYMBOl_ZOOMS_NORMAL,
			'symbol-file'  => 'boundary_stone',
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-color' => $_SYMBOL_HISTORIC_COLOR,
			'text-color'   => $_SYMBOL_HISTORIC_COLOR,
			'symbol-halo'  => $_SYMBOL_HISTORIC_HALO_COLOR,
			'halo-color'   => $_SYMBOL_HISTORIC_HALO_COLOR,
		),	
	"[historic='battlefield']" => array(			
			'zooms'        => $_SYMBOl_ZOOMS_NORMAL,
			'symbol-file'  => 'battlefield',
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_SMALL,
			'symbol-color' => $_SYMBOL_HISTORIC_COLOR,
			'text-color'   => $_SYMBOL_HISTORIC_COLOR,
			'symbol-halo'  => $_SYMBOL_HISTORIC_HALO_COLOR,
			'halo-color'   => $_SYMBOL_HISTORIC_HALO_COLOR,
		),		
		
	"[man_made='tower'][\"tower:type\"='observation'],[man_made='tower'][tourism='attraction']" => array(			
			'zooms'        => $_SYMBOl_ZOOMS_BIG,
			'symbol-file'  => 'tower-observation',
			'symbol-size'  => $_SYMBOl_SIZE_BIG,
			'text-size'    => $_SYMBOl_TEXT_SIZE_BIG,
			'symbol-color' => $_SYMBOL_HISTORIC_COLOR,
			'text-color'   => $_SYMBOL_HISTORIC_COLOR,
			'symbol-halo'  => $_SYMBOL_HISTORIC_HALO_COLOR,
			'halo-color'   => $_SYMBOL_HISTORIC_HALO_COLOR,
		),
	"[man_made='lighthouse']" => array(			
			'zooms'        => $_SYMBOl_ZOOMS_BIG,
			'symbol-file'  => 'lighthouse',
			'symbol-size'  => $_SYMBOl_SIZE_NORMAL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_NORMAL,
			'symbol-color' => $_SYMBOL_HISTORIC_COLOR,
			'text-color'   => $_SYMBOL_HISTORIC_COLOR,
			'symbol-halo'  => $_SYMBOL_HISTORIC_HALO_COLOR,
			'halo-color'   => $_SYMBOL_HISTORIC_HALO_COLOR,
		),
	
	"[man_made='tower'][\"tower:type\"='communication']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_NORMAL,
			'symbol-file'  => 'tower-comunication',
			'symbol-size'  => $_SYMBOl_SIZE_NORMAL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_NORMAL,
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),	
	"[man_made='water_tower']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_NORMAL,
			'symbol-file'  => 'tower-water',
			'symbol-size'  => $_SYMBOl_SIZE_NORMAL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_NORMAL,
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
	"[tourism='viewpoint']" => array(			
			'zooms'        => $_SYMBOl_ZOOMS_NORMAL,
			'symbol-file'  => 'viewpoint',
			'symbol-size'  => $_SYMBOl_SIZE_NORMAL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_NORMAL,
			'symbol-color' => $_SYMBOL_HISTORIC_COLOR,
			'text-color'   => $_SYMBOL_HISTORIC_COLOR,
			'symbol-halo'  => $_SYMBOL_HISTORIC_HALO_COLOR,
			'halo-color'   => $_SYMBOL_HISTORIC_HALO_COLOR,
		),	
	"[tourism='museum']" => array(			
			'zooms'        => $_SYMBOl_ZOOMS_BIG,
			'symbol-file'  => 'museum',
			'symbol-size'  => $_SYMBOl_SIZE_NORMAL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_NORMAL,
			'symbol-color' => $_SYMBOL_HISTORIC_COLOR,
			'text-color'   => $_SYMBOL_HISTORIC_COLOR,
			'symbol-halo'  => $_SYMBOL_HISTORIC_HALO_COLOR,
			'halo-color'   => $_SYMBOL_HISTORIC_HALO_COLOR,
		),	
		
	"[tourism='zoo']" => array(			
			'zooms'        => $_SYMBOl_ZOOMS_BIG,
			'symbol-file'  => 'zoo',
			'symbol-size'  => $_SYMBOl_SIZE_BIG,
			'text-size'    => $_SYMBOl_TEXT_SIZE_BIG,
			'symbol-color' => $_SYMBOL_HISTORIC_COLOR,
			'text-color'   => $_SYMBOL_HISTORIC_COLOR,
			'symbol-halo'  => $_SYMBOL_HISTORIC_HALO_COLOR,
			'halo-color'   => $_SYMBOL_HISTORIC_HALO_COLOR,
		),	
		
	"[tourism='camp_site']" => array(			
			'zooms'        => $_SYMBOl_ZOOMS_HUGELOW,
			'symbol-file'  => 'camp',
			'symbol-size'  => $_SYMBOl_SIZE_NORMAL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_SMALL,
			'symbol-color' => $_SYMBOL_HISTORIC_COLOR,
			'text-color'   => $_SYMBOL_HISTORIC_COLOR,
			'symbol-halo'  => $_SYMBOL_HISTORIC_HALO_COLOR,
			'halo-color'   => $_SYMBOL_HISTORIC_HALO_COLOR,		
		),	
	"[tourism='information'][information='guidepost']" => array(			
			'zooms'        => $_SYMBOl_ZOOMS_BIG,
			'symbol-file'  => 'information-guidepost',
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_SMALL,
			'symbol-color' => $_SYMBOL_HISTORIC_COLOR,
			'text-color'   => $_SYMBOL_HISTORIC_COLOR,
			'symbol-halo'  => $_SYMBOL_HISTORIC_HALO_COLOR,
			'halo-color'   => $_SYMBOL_HISTORIC_HALO_COLOR,		
		),	
	"[tourism='information'][information='board']" => array(			
			'zooms'        => $_SYMBOl_ZOOMS_NORMAL,
			'symbol-file'  => 'information-board',
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_SMALL,
			'symbol-color' => $_SYMBOL_HISTORIC_COLOR,
			'text-color'   => $_SYMBOL_HISTORIC_COLOR,
			'symbol-halo'  => $_SYMBOL_HISTORIC_HALO_COLOR,
			'halo-color'   => $_SYMBOL_HISTORIC_HALO_COLOR,	
		),	
	"[tourism='information'][information='map']" => array(			
			'zooms'        => $_SYMBOl_ZOOMS_NORMAL,
			'symbol-file'  => 'information-map',
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_SMALL,
			'symbol-color' => $_SYMBOL_HISTORIC_COLOR,
			'text-color'   => $_SYMBOL_HISTORIC_COLOR,
			'symbol-halo'  => $_SYMBOL_HISTORIC_HALO_COLOR,
			'halo-color'   => $_SYMBOL_HISTORIC_HALO_COLOR,	
		),	
	"[tourism='information'][information='office']" => array(			
			'zooms'        => $_SYMBOl_ZOOMS_NORMAL,
			'symbol-file'  => 'information-office',
			'symbol-size'  => $_SYMBOl_SIZE_NORMAL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_NORMAL,
			'symbol-color' => $_SYMBOL_HISTORIC_COLOR,
			'text-color'   => $_SYMBOL_HISTORIC_COLOR,
			'symbol-halo'  => $_SYMBOL_HISTORIC_HALO_COLOR,
			'halo-color'   => $_SYMBOL_HISTORIC_HALO_COLOR,	
		),	
	"[tourism='artwork']" => array(			
			'zooms'        => $_SYMBOl_ZOOMS_NORMAL,
			'symbol-file'  => 'artwork-statue',
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-color' => $_SYMBOL_HISTORIC_COLOR,
			'text-color'   => $_SYMBOL_HISTORIC_COLOR,
			'symbol-halo'  => $_SYMBOL_HISTORIC_HALO_COLOR,
			'halo-color'   => $_SYMBOL_HISTORIC_HALO_COLOR,	
		),
	"[amenity='atm']" => array(			
			'zooms'        => $_SYMBOl_ZOOMS_TINY,
			'symbol-file'  => 'atm',
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
	"[amenity='bank']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,
			'symbol-file'  => 'bank',
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_SMALL,
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
	"[amenity='bench']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_TINY,
			'symbol-file'  => 'bench',
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
	"[natural='cave_entrance']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_BIG,
			'symbol-file'  => 'cave',
			'symbol-size'  => $_SYMBOl_SIZE_BIG,
			'text-size'    => $_SYMBOl_TEXT_SIZE_BIG,
			'symbol-color' => $_SYMBOL_NATURAL_COLOR,
			'text-color'   => $_SYMBOL_NATURAL_COLOR,
			'symbol-halo'  => $_SYMBOL_NATURAL_HALO_COLOR,
			'halo-color'   => $_SYMBOL_NATURAL_HALO_COLOR,
		),	
	"[amenity='doctors'],[amenity='dentist']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,
			'symbol-file'  => 'doctors',
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
	"[amenity='hospital']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,
			'symbol-file'  => 'hospital',
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_SMALL,
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
	"[amenity='clinic'],[amenity='nursing_home']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,
			'symbol-file'  => 'hospital',
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
	"[amenity='drinking_water']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_TINY,
			'symbol-file'  => 'drinking-water',
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-color' => $_SYMBOL_HISTORIC_COLOR,
			'text-color'   => $_SYMBOL_HISTORIC_COLOR,
			'symbol-halo'  => $_SYMBOL_HISTORIC_HALO_COLOR,
			'halo-color'   => $_SYMBOL_HISTORIC_HALO_COLOR,	
		),
	"[amenity='fuel']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_HUGELOW,
			'symbol-file'  => 'fuel',
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_SMALL,
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
	"[tourism='guest_house'],[tourism='hostel'],[tourism='motel'],[tourism='hut'],[tourism='alpine_hut']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_NORMAL,
			'symbol-file'  => 'guest-house',
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_SMALL,
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
	"[tourism='hotel']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_NORMAL,
			'symbol-file'  => 'hotel',
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_SMALL,
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
		
	"[man_made='hunting_stand'],[amenity='hunting_stand']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,
			'symbol-file'  => 'hunting-stand',
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),	
	"[amenity='parking']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_BIG,
			'symbol-file'  => 'parking',
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-color' => $_SYMBOL_TRANSPORT_COLOR,
			'text-color'   => $_SYMBOL_TRANSPORT_COLOR,
			'symbol-halo'  => $_SYMBOL_TRANSPORT_HALO_COLOR,
			'halo-color'   => $_SYMBOL_TRANSPORT_HALO_COLOR,
		),
	"[amenity='parking_entrance']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_BIG,
			'symbol-file'  => 'parking_entrance',
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-color' => $_SYMBOL_TRANSPORT_COLOR,
			'text-color'   => $_SYMBOL_TRANSPORT_COLOR,
			'symbol-halo'  => $_SYMBOL_TRANSPORT_HALO_COLOR,
			'halo-color'   => $_SYMBOL_TRANSPORT_HALO_COLOR,
		),
	"[amenity='pharmacy']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_TINY,
			'symbol-file'  => 'pharmacy',
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
	"[tourism='picnic_site'],[leisure='picnic_table']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,
			'symbol-file'  => 'picnic',
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
	"[amenity='post_box']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_TINY,
			'symbol-file'  => 'postbox',
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
	"[amenity='post_office']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,
			'symbol-file'  => 'postoffice',
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_SMALL,
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
	"[amenity='pub'],[amenity='bar'],[amenity='nightclub']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,
			'symbol-file'  => 'pub',
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_SMALL,
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
	"[amenity='cafe']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,
			'symbol-file'  => 'cafe',
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_SMALL,
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
	),
	"[amenity='restaurant'],[amenity='fast_food'],[amenity='biergarten']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,
			'symbol-file'  => 'restaurant',
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_SMALL,
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
	"[amenity='shelter']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,
			'symbol-file'  => 'shelter',
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
	"[natural='spring']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_NORMAL,
			'symbol-file'  => 'spring',
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-color' => $_SYMBOL_NATURAL_COLOR,
			'text-color'   => $_SYMBOL_NATURAL_COLOR,
			'symbol-halo'  => $_SYMBOL_NATURAL_HALO_COLOR,
			'halo-color'   => $_SYMBOL_NATURAL_HALO_COLOR,
		),
	"[amenity='theatre']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_BIG,
			'symbol-file'  => 'theatre',
			'symbol-size'  => $_SYMBOl_SIZE_NORMAL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_NORMAL,
			'symbol-color' => $_SYMBOL_HISTORIC_COLOR,
			'text-color'   => $_SYMBOL_HISTORIC_COLOR,
			'symbol-halo'  => $_SYMBOL_HISTORIC_HALO_COLOR,
			'halo-color'   => $_SYMBOL_HISTORIC_HALO_COLOR,
		),	
	"[man_made='watermill']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_BIG,
			'symbol-file'  => 'watermill',
			'symbol-size'  => $_SYMBOl_SIZE_NORMAL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_NORMAL,
			'symbol-color' => $_SYMBOL_HISTORIC_COLOR,
			'text-color'   => $_SYMBOL_HISTORIC_COLOR,
			'symbol-halo'  => $_SYMBOL_HISTORIC_HALO_COLOR,
			'halo-color'   => $_SYMBOL_HISTORIC_HALO_COLOR,
		),	
	"[man_made='water_well']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_BIG,
			'symbol-file'  => 'waterwell',
			'symbol-size'  => $_SYMBOl_SIZE_NORMAL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_NORMAL,
			'symbol-color' => $_SYMBOL_HISTORIC_COLOR,
			'text-color'   => $_SYMBOL_HISTORIC_COLOR,
			'symbol-halo'  => $_SYMBOL_HISTORIC_HALO_COLOR,
			'halo-color'   => $_SYMBOL_HISTORIC_HALO_COLOR,
		),	
	"[man_made='windmill']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_BIG,
			'symbol-file'  => 'windmill',
			'symbol-size'  => $_SYMBOl_SIZE_NORMAL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_NORMAL,
			'symbol-color' => $_SYMBOL_HISTORIC_COLOR,
			'text-color'   => $_SYMBOL_HISTORIC_COLOR,
			'symbol-halo'  => $_SYMBOL_HISTORIC_HALO_COLOR,
			'halo-color'   => $_SYMBOL_HISTORIC_HALO_COLOR,
		),	
	"[amenity='fountain']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_NORMAL,
			'symbol-file'  => 'fontain',
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_SMALL,
			'symbol-color' => $_SYMBOL_HISTORIC_COLOR,
			'text-color'   => $_SYMBOL_HISTORIC_COLOR,
			'symbol-halo'  => $_SYMBOL_HISTORIC_HALO_COLOR,
			'halo-color'   => $_SYMBOL_HISTORIC_HALO_COLOR,	
		),	
	"[railway='tram_stop']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_NORMAL,			
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'tram_stop',		
			'symbol-color' => $_SYMBOL_TRANSPORT_COLOR,
			'text-color'   => $_SYMBOL_TRANSPORT_COLOR,
			'symbol-halo'  => $_SYMBOL_TRANSPORT_HALO_COLOR,
			'halo-color'   => $_SYMBOL_TRANSPORT_HALO_COLOR,
			'halo-opacity' => $_SYMBOL_TRANSPORT_HALO_OPACITY,
		),
	"[highway='bus_stop']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_BIG,			
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'bus_stop',		
			'symbol-color' => $_SYMBOL_TRANSPORT_COLOR,
			'text-color'   => $_SYMBOL_TRANSPORT_COLOR,
			'symbol-halo'  => $_SYMBOL_TRANSPORT_HALO_COLOR,
			'halo-color'   => $_SYMBOL_TRANSPORT_HALO_COLOR,
			'halo-opacity' => $_SYMBOL_TRANSPORT_HALO_OPACITY,
		),
	"[aeroway='aerodrome']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_HUGE,			
			'symbol-size'  => $_SYMBOl_SIZE_HUGE,
			'text-size'    => $_SYMBOl_TEXT_SIZE_HUGE,
			'symbol-file'  => 'aerodrom',		
			'symbol-color' => $_SYMBOL_TRANSPORT_COLOR,
			'text-color'   => $_SYMBOL_TRANSPORT_COLOR,
			'symbol-halo'  => $_SYMBOL_TRANSPORT_HALO_COLOR,
			'halo-color'   => $_SYMBOL_TRANSPORT_HALO_COLOR,	
			'halo-opacity' => $_SYMBOL_TRANSPORT_HALO_OPACITY,
		),
	"[railway='subway_entrance']" => array(
			'zooms'        => array(12 => 4, 13 => 4, 14 => 4, 15 => 3, 16 => 1, 17 => 1, 18 => 1),			
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'subway_entrance',		
			'symbol-color' => $_SYMBOL_TRANSPORT_COLOR,
			'text-color'   => $_SYMBOL_TRANSPORT_COLOR,
			'symbol-halo'  => $_SYMBOL_TRANSPORT_HALO_COLOR,
			'halo-color'   => $_SYMBOL_TRANSPORT_HALO_COLOR,	
			'halo-opacity' => $_SYMBOL_TRANSPORT_HALO_OPACITY,
		),
	"[railway='halt']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_HUGE,			
			'symbol-size'  => $_SYMBOl_SIZE_NORMAL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_NORMAL,
			'symbol-file'  => 'station',		
			'symbol-color' => $_SYMBOL_TRANSPORT_COLOR,
			'text-color'   => $_SYMBOL_TRANSPORT_COLOR,
			'symbol-halo'  => $_SYMBOL_TRANSPORT_HALO_COLOR,
			'halo-color'   => $_SYMBOL_TRANSPORT_HALO_COLOR,
			'halo-opacity' => $_SYMBOL_TRANSPORT_HALO_OPACITY,
		),
	"[amenity='ferry_terminal']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_HUGE,			
			'symbol-size'  => $_SYMBOl_SIZE_NORMAL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_SMALL,
			'symbol-file'  => 'ferry_terminal',		
			'symbol-color' => $_SYMBOL_TRANSPORT_COLOR,
			'text-color'   => $_SYMBOL_TRANSPORT_COLOR,
			'symbol-halo'  => $_SYMBOL_TRANSPORT_HALO_COLOR,
			'halo-color'   => $_SYMBOL_TRANSPORT_HALO_COLOR,
			'halo-opacity' => $_SYMBOL_TRANSPORT_HALO_COLOR,
		),
	"[railway='station'][transport!='subway']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_HUGE,			
			'symbol-size'  => $_SYMBOl_SIZE_BIG,
			'text-size'    => $_SYMBOl_TEXT_SIZE_BIG,
			'symbol-file'  => 'station',		
			'symbol-color' => $_SYMBOL_TRANSPORT_COLOR,
			'text-color'   => $_SYMBOL_TRANSPORT_COLOR,
			'symbol-halo'  => $_SYMBOL_TRANSPORT_HALO_COLOR,
			'halo-color'   => $_SYMBOL_TRANSPORT_HALO_COLOR,
			'halo-opacity' => $_SYMBOL_TRANSPORT_HALO_OPACITY,
		),	
		"[railway='station'][transport='subway']" => array(
			'zooms'        => array(12 => 2, 13 => 1, 14 => 1, 15 => 2, 16 => 4, 17 => 4, 18 => 4),			
			'symbol-size'  => $_SYMBOl_SIZE_NORMAL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_NORMAL,
			'symbol-file'  => 'subway',		
			'symbol-color' => $_SYMBOL_TRANSPORT_COLOR,
			'text-color'   => $_SYMBOL_TRANSPORT_COLOR,
			'symbol-halo'  => $_SYMBOL_TRANSPORT_HALO_COLOR,
			'halo-color'   => $_SYMBOL_TRANSPORT_HALO_COLOR,
			'halo-opacity' => $_SYMBOL_TRANSPORT_HALO_OPACITY,
		),
		"[amenity='car_rental']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_BIG,			
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'car_rental',		
			'symbol-color' => $_SYMBOL_TRANSPORT_COLOR,
			'text-color'   => $_SYMBOL_TRANSPORT_COLOR,
			'symbol-halo'  => $_SYMBOL_TRANSPORT_HALO_COLOR,
			'halo-color'   => $_SYMBOL_TRANSPORT_HALO_COLOR,
			'halo-opacity' => $_SYMBOL_TRANSPORT_HALO_OPACITY,
		),
		"[amenity='car_sharing']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_NORMAL,			
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'car_sharing',		
			'symbol-color' => $_SYMBOL_TRANSPORT_COLOR,
			'text-color'   => $_SYMBOL_TRANSPORT_COLOR,
			'symbol-halo'  => $_SYMBOL_TRANSPORT_HALO_COLOR,
			'halo-color'   => $_SYMBOL_TRANSPORT_HALO_COLOR,
			'halo-opacity' => $_SYMBOL_TRANSPORT_HALO_OPACITY,
		),
		"[amenity='school']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'school',		
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),		
		"[amenity='kindergarten']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'school',		
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
		"[amenity='recycling'],[amenity='waste_basket']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_TINY,			
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'recycling',		
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
		"[amenity='clock']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_TINY,			
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'clock',		
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
		"[amenity='icecream']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_TINY,			
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'icecream',		
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,			
		),
		"[amenity='bicycle_parking']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'bicycle_parking',		
			'symbol-color' => $_SYMBOL_TRANSPORT_COLOR,
			'text-color'   => $_SYMBOL_TRANSPORT_COLOR,
			'symbol-halo'  => $_SYMBOL_TRANSPORT_HALO_COLOR,
			'halo-color'   => $_SYMBOL_TRANSPORT_HALO_COLOR,
			'halo-opacity' => $_SYMBOL_TRANSPORT_HALO_OPACITY,
		),
		"[amenity='motorcycle_parking']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'motorcycle_parking',		
			'symbol-color' => $_SYMBOL_TRANSPORT_COLOR,
			'text-color'   => $_SYMBOL_TRANSPORT_COLOR,
			'symbol-halo'  => $_SYMBOL_TRANSPORT_HALO_COLOR,
			'halo-color'   => $_SYMBOL_TRANSPORT_HALO_COLOR,
			'halo-opacity' => $_SYMBOL_TRANSPORT_HALO_OPACITY,
		),		
		"[amenity='telephone']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_TINY,			
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'telephone',		
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
		"[amenity='fire_hydrant']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_TINY,			
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'fire_hydrant',		
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
		"[amenity='toilets']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'toilets',		
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
		"[amenity='shower']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_TINY,
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'shower',		
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
		"[amenity='taxi']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'taxi',		
			'symbol-color' => $_SYMBOL_TRANSPORT_COLOR,
			'text-color'   => $_SYMBOL_TRANSPORT_COLOR,
			'symbol-halo'  => $_SYMBOL_TRANSPORT_HALO_COLOR,
			'halo-color'   => $_SYMBOL_TRANSPORT_HALO_COLOR,
		),
		"[amenity='car_wash']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'car_wash',		
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
		"[amenity='public_building'],[amenity='comunity_centre']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_SMALL,
			'symbol-file'  => 'public_building',		
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
		"[amenity='fire_station']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_SMALL,
			'symbol-file'  => 'fire_station',		
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
		"[amenity='police']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_SMALL,
			'symbol-file'  => 'police',		
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
		"[amenity='swimming_pool']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_BIG,			
			'symbol-size'  => $_SYMBOl_SIZE_NORMAL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_SMALL,
			'symbol-file'  => 'swiming_pool',		
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
		"[amenity='townhall']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_NORMAL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_SMALL,
			'symbol-file'  => 'townhall',		
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
		"[amenity='library']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_NORMAL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_SMALL,
			'symbol-file'  => 'library',		
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
		"[amenity='university'],[amenity='college']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_NORMAL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_SMALL,
			'symbol-file'  => 'university',		
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
		"[amenity='social_facility']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_NORMAL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_SMALL,
			'symbol-file'  => 'university',		
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
		"[amenity='marketplace']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_NORMAL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_SMALL,
			'symbol-file'  => 'marketplace',		
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
		"[amenity='cinema']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_NORMAL,			
			'symbol-size'  => $_SYMBOl_SIZE_NORMAL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_SMALL,
			'symbol-file'  => 'cinema',		
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),		
		"[amenity='veterinary']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_NORMAL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_SMALL,
			'symbol-file'  => 'veterinary',		
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
		"[amenity='courthouse']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_NORMAL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_SMALL,
			'symbol-file'  => 'courthouse',		
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
		"[amenity='prison']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_NORMAL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_SMALL,
			'symbol-file'  => 'prison',		
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
		"[amenity='arts_centre']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_NORMAL,			
			'symbol-size'  => $_SYMBOl_SIZE_NORMAL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_SMALL,
			'symbol-file'  => 'arts_centre',		
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
		"[amenity='embassy']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_BIG,			
			'symbol-size'  => $_SYMBOl_SIZE_NORMAL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_NORMAL,
			'symbol-file'  => 'embassy',		
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
		"[amenity='driving_school']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_NORMAL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_SMALL,
			'symbol-file'  => 'driving_school',		
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
		"[amenity='studio']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_NORMAL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_SMALL,
			'symbol-file'  => 'studio',		
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
		"[amenity='brothel']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_NORMAL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_SMALL,
			'symbol-file'  => 'brothel',		
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
		"[amenity='sauna']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_NORMAL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_SMALL,
			'symbol-file'  => 'sauna',		
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
		"[amenity='retirement_home']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_NORMAL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_SMALL,
			'symbol-file'  => 'retirement_home',		
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
		"[shop='supermarket']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'supermarket',		
			'symbol-color' => $_SYMBOL_SHOP_COLOR,
			'text-color'   => $_SYMBOL_SHOP_COLOR,
			'symbol-halo'  => $_SYMBOL_SHOP_HALO_COLOR,
			'halo-color'   => $_SYMBOL_SHOP_HALO_COLOR,
		),
		"[shop='convenience']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'convenience',		
			'symbol-color' => $_SYMBOL_SHOP_COLOR,
			'text-color'   => $_SYMBOL_SHOP_COLOR,
			'symbol-halo'  => $_SYMBOL_SHOP_HALO_COLOR,
			'halo-color'   => $_SYMBOL_SHOP_HALO_COLOR,
		),
		"[shop='clothes']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'clothes',		
			'symbol-color' => $_SYMBOL_SHOP_COLOR,
			'text-color'   => $_SYMBOL_SHOP_COLOR,
			'symbol-halo'  => $_SYMBOL_SHOP_HALO_COLOR,
			'halo-color'   => $_SYMBOL_SHOP_HALO_COLOR,
		),
		"[shop='bakery']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'bakery',		
			'symbol-color' => $_SYMBOL_SHOP_COLOR,
			'text-color'   => $_SYMBOL_SHOP_COLOR,
			'symbol-halo'  => $_SYMBOL_SHOP_HALO_COLOR,
			'halo-color'   => $_SYMBOL_SHOP_HALO_COLOR,
		),
		"[shop='hairdresser']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'hairdresser',		
			'symbol-color' => $_SYMBOL_SHOP_COLOR,
			'text-color'   => $_SYMBOL_SHOP_COLOR,
			'symbol-halo'  => $_SYMBOL_SHOP_HALO_COLOR,
			'halo-color'   => $_SYMBOL_SHOP_HALO_COLOR,
		),
		"[shop='car_repair']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'car_repair',		
			'symbol-color' => $_SYMBOL_SHOP_COLOR,
			'text-color'   => $_SYMBOL_SHOP_COLOR,
			'symbol-halo'  => $_SYMBOL_SHOP_HALO_COLOR,
			'halo-color'   => $_SYMBOL_SHOP_HALO_COLOR,

		),
		"[shop='car']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'car',		
			'symbol-color' => $_SYMBOL_SHOP_COLOR,
			'text-color'   => $_SYMBOL_SHOP_COLOR,
			'symbol-halo'  => $_SYMBOL_SHOP_HALO_COLOR,
			'halo-color'   => $_SYMBOL_SHOP_HALO_COLOR,
		),
		"[shop='kiosk']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'kiosk',		
			'symbol-color' => $_SYMBOL_SHOP_COLOR,
			'text-color'   => $_SYMBOL_SHOP_COLOR,
			'symbol-halo'  => $_SYMBOL_SHOP_HALO_COLOR,
			'halo-color'   => $_SYMBOL_SHOP_HALO_COLOR,
		),		
		"[shop='butcher']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'butcher',		
			'symbol-color' => $_SYMBOL_SHOP_COLOR,
			'text-color'   => $_SYMBOL_SHOP_COLOR,
			'symbol-halo'  => $_SYMBOL_SHOP_HALO_COLOR,
			'halo-color'   => $_SYMBOL_SHOP_HALO_COLOR,
		),
		"[shop='florist']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'florist',		
			'symbol-color' => $_SYMBOL_SHOP_COLOR,
			'text-color'   => $_SYMBOL_SHOP_COLOR,
			'symbol-halo'  => $_SYMBOL_SHOP_HALO_COLOR,
			'halo-color'   => $_SYMBOL_SHOP_HALO_COLOR,
		),
		"[shop='alcohol']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'alcohol',		
			'symbol-color' => $_SYMBOL_SHOP_COLOR,
			'text-color'   => $_SYMBOL_SHOP_COLOR,
			'symbol-halo'  => $_SYMBOL_SHOP_HALO_COLOR,
			'halo-color'   => $_SYMBOL_SHOP_HALO_COLOR,
		),
		"[shop='mall']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_BIG,			
			'symbol-size'  => $_SYMBOl_SIZE_BIG,
			'text-size'    => $_SYMBOl_TEXT_SIZE_BIG,
			'symbol-file'  => 'department_store',		
			'symbol-color' => $_SYMBOL_SHOP_COLOR,
			'text-color'   => $_SYMBOL_SHOP_COLOR,
			'symbol-halo'  => $_SYMBOL_SHOP_HALO_COLOR,
			'halo-color'   => $_SYMBOL_SHOP_HALO_COLOR,
		),
		"[shop='bicycle']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'bicycle',		
			'symbol-color' => $_SYMBOL_SHOP_COLOR,
			'text-color'   => $_SYMBOL_SHOP_COLOR,
			'symbol-halo'  => $_SYMBOL_SHOP_HALO_COLOR,
			'halo-color'   => $_SYMBOL_SHOP_HALO_COLOR,
		),
		"[shop='furniture']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'furniture',		
			'symbol-color' => $_SYMBOL_SHOP_COLOR,
			'text-color'   => $_SYMBOL_SHOP_COLOR,
			'symbol-halo'  => $_SYMBOL_SHOP_HALO_COLOR,
			'halo-color'   => $_SYMBOL_SHOP_HALO_COLOR,
		),
		"[shop='books']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'books',		
			'symbol-color' => $_SYMBOL_SHOP_COLOR,
			'text-color'   => $_SYMBOL_SHOP_COLOR,
			'symbol-halo'  => $_SYMBOL_SHOP_HALO_COLOR,
			'halo-color'   => $_SYMBOL_SHOP_HALO_COLOR,
		),		
		"[shop='electronics']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'electronics',		
			'symbol-color' => $_SYMBOL_SHOP_COLOR,
			'text-color'   => $_SYMBOL_SHOP_COLOR,
			'symbol-halo'  => $_SYMBOL_SHOP_HALO_COLOR,
			'halo-color'   => $_SYMBOL_SHOP_HALO_COLOR,
		),
		"[shop='shoes']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'shoes',		
			'symbol-color' => $_SYMBOL_SHOP_COLOR,
			'text-color'   => $_SYMBOL_SHOP_COLOR,
			'symbol-halo'  => $_SYMBOL_SHOP_HALO_COLOR,
			'halo-color'   => $_SYMBOL_SHOP_HALO_COLOR,
		),
		"[shop='department_store']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_BIG,			
			'symbol-size'  => $_SYMBOl_SIZE_BIG,
			'text-size'    => $_SYMBOl_TEXT_SIZE_BIG,
			'symbol-file'  => 'department_store',		
			'symbol-color' => $_SYMBOL_SHOP_COLOR,
			'text-color'   => $_SYMBOL_SHOP_COLOR,
			'symbol-halo'  => $_SYMBOL_SHOP_HALO_COLOR,
			'halo-color'   => $_SYMBOL_SHOP_HALO_COLOR,
		),
		"[shop='hardware']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'electronics',		
			'symbol-color' => $_SYMBOL_SHOP_COLOR,
			'text-color'   => $_SYMBOL_SHOP_COLOR,
			'symbol-halo'  => $_SYMBOL_SHOP_HALO_COLOR,
			'halo-color'   => $_SYMBOL_SHOP_HALO_COLOR,
		),
		"[shop='optician']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'optician',		
			'symbol-color' => $_SYMBOL_SHOP_COLOR,
			'text-color'   => $_SYMBOL_SHOP_COLOR,
			'symbol-halo'  => $_SYMBOL_SHOP_HALO_COLOR,
			'halo-color'   => $_SYMBOL_SHOP_HALO_COLOR,
		),
		"[shop='jewelry']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'jewelry',		
			'symbol-color' => $_SYMBOL_SHOP_COLOR,
			'text-color'   => $_SYMBOL_SHOP_COLOR,
			'symbol-halo'  => $_SYMBOL_SHOP_HALO_COLOR,
			'halo-color'   => $_SYMBOL_SHOP_HALO_COLOR,
		),
		"[shop='chemist']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'chemist',		
			'symbol-color' => $_SYMBOL_SHOP_COLOR,
			'text-color'   => $_SYMBOL_SHOP_COLOR,
			'symbol-halo'  => $_SYMBOL_SHOP_HALO_COLOR,
			'halo-color'   => $_SYMBOL_SHOP_HALO_COLOR,
		),
		"[shop='gift']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'gift',		
			'symbol-color' => $_SYMBOL_SHOP_COLOR,
			'text-color'   => $_SYMBOL_SHOP_COLOR,
			'symbol-halo'  => $_SYMBOL_SHOP_HALO_COLOR,
			'halo-color'   => $_SYMBOL_SHOP_HALO_COLOR,
		),
		"[shop='garden_centre']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'garden_centre',		
			'symbol-color' => $_SYMBOL_SHOP_COLOR,
			'text-color'   => $_SYMBOL_SHOP_COLOR,
			'symbol-halo'  => $_SYMBOL_SHOP_HALO_COLOR,
			'halo-color'   => $_SYMBOL_SHOP_HALO_COLOR,
		),
		"[shop='greengrocer']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'greengrocer',		
			'symbol-color' => $_SYMBOL_SHOP_COLOR,
			'text-color'   => $_SYMBOL_SHOP_COLOR,
			'symbol-halo'  => $_SYMBOL_SHOP_HALO_COLOR,
			'halo-color'   => $_SYMBOL_SHOP_HALO_COLOR,
		),
		"[shop='mobile_phone']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'mobile_phone',		
			'symbol-color' => $_SYMBOL_SHOP_COLOR,
			'text-color'   => $_SYMBOL_SHOP_COLOR,
			'symbol-halo'  => $_SYMBOL_SHOP_HALO_COLOR,
			'halo-color'   => $_SYMBOL_SHOP_HALO_COLOR,
		),
		"[shop='beverages']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'beverages',		
			'symbol-color' => $_SYMBOL_SHOP_COLOR,
			'text-color'   => $_SYMBOL_SHOP_COLOR,
			'symbol-halo'  => $_SYMBOL_SHOP_HALO_COLOR,
			'halo-color'   => $_SYMBOL_SHOP_HALO_COLOR,
		),
		"[shop='computer']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'electronics',		
			'symbol-color' => $_SYMBOL_SHOP_COLOR,
			'text-color'   => $_SYMBOL_SHOP_COLOR,
			'symbol-halo'  => $_SYMBOL_SHOP_HALO_COLOR,
			'halo-color'   => $_SYMBOL_SHOP_HALO_COLOR,
		),		
		"[shop='sports']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'multi',		
			'symbol-color' => $_SYMBOL_SHOP_COLOR,
			'text-color'   => $_SYMBOL_SHOP_COLOR,
			'symbol-halo'  => $_SYMBOL_SHOP_HALO_COLOR,
		),
		"[shop='laundry']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'laundry',		
			'symbol-color' => $_SYMBOL_SHOP_COLOR,
			'text-color'   => $_SYMBOL_SHOP_COLOR,
			'symbol-halo'  => $_SYMBOL_SHOP_HALO_COLOR,
			'halo-color'   => $_SYMBOL_SHOP_HALO_COLOR,
		),
		"[shop='toys']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'toys',		
			'symbol-color' => $_SYMBOL_SHOP_COLOR,
			'text-color'   => $_SYMBOL_SHOP_COLOR,
			'symbol-halo'  => $_SYMBOL_SHOP_HALO_COLOR,
			'halo-color'   => $_SYMBOL_SHOP_HALO_COLOR,
		),
		"[shop='confectionery']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'confectionery',		
			'symbol-color' => $_SYMBOL_SHOP_COLOR,
			'text-color'   => $_SYMBOL_SHOP_COLOR,
			'symbol-halo'  => $_SYMBOL_SHOP_HALO_COLOR,
			'halo-color'   => $_SYMBOL_SHOP_HALO_COLOR,
		),
		"[shop='travel_agency']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'travel_agency',		
			'symbol-color' => $_SYMBOL_SHOP_COLOR,
			'text-color'   => $_SYMBOL_SHOP_COLOR,
			'symbol-halo'  => $_SYMBOL_SHOP_HALO_COLOR,
			'halo-color'   => $_SYMBOL_SHOP_HALO_COLOR,
		),
		"[shop='stationery']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'supermarket',		
			'symbol-color' => $_SYMBOL_SHOP_COLOR,
			'text-color'   => $_SYMBOL_SHOP_COLOR,
			'symbol-halo'  => $_SYMBOL_SHOP_HALO_COLOR,
			'halo-color'   => $_SYMBOL_SHOP_HALO_COLOR,
		),
		"[shop='hifi']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'hifi',		
			'symbol-color' => $_SYMBOL_SHOP_COLOR,
			'text-color'   => $_SYMBOL_SHOP_COLOR,
			'symbol-halo'  => $_SYMBOL_SHOP_HALO_COLOR,
			'halo-color'   => $_SYMBOL_SHOP_HALO_COLOR,
		),		
		"[shop='dry_cleaning']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'dry_cleaning',		
			'symbol-color' => $_SYMBOL_SHOP_COLOR,
			'text-color'   => $_SYMBOL_SHOP_COLOR,
			'symbol-halo'  => $_SYMBOL_SHOP_HALO_COLOR,
			'halo-color'   => $_SYMBOL_SHOP_HALO_COLOR,
		),
		"[shop='variety_store']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'variety_store',		
			'symbol-color' => $_SYMBOL_SHOP_COLOR,
			'text-color'   => $_SYMBOL_SHOP_COLOR,
			'symbol-halo'  => $_SYMBOL_SHOP_HALO_COLOR,
			'halo-color'   => $_SYMBOL_SHOP_HALO_COLOR,
		),	
		"[sport='soccer'],[sport='football']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'soccer',		
			'symbol-color' => $_SYMBOL_SPORT_COLOR,
			'text-color'   => $_SYMBOL_SPORT_COLOR,
			'symbol-halo'  => $_SYMBOL_SPORT_HALO_COLOR,
			'halo-color'   => $_SYMBOL_SPORT_HALO_COLOR,
		),
		"[sport='tennis']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'tennis',		
			'symbol-color' => $_SYMBOL_SPORT_COLOR,
			'text-color'   => $_SYMBOL_SPORT_COLOR,
			'symbol-halo'  => $_SYMBOL_SPORT_HALO_COLOR,
			'halo-color'   => $_SYMBOL_SPORT_HALO_COLOR,
		),		
		"[sport='baseball']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'baseball',		
			'symbol-color' => $_SYMBOL_SPORT_COLOR,
			'text-color'   => $_SYMBOL_SPORT_COLOR,
			'symbol-halo'  => $_SYMBOL_SPORT_HALO_COLOR,
			'halo-color'   => $_SYMBOL_SPORT_HALO_COLOR,
		),		
		"[sport='swimming']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'swimming',		
			'symbol-color' => $_SYMBOL_SPORT_COLOR,
			'text-color'   => $_SYMBOL_SPORT_COLOR,
			'symbol-halo'  => $_SYMBOL_SPORT_HALO_COLOR,
			'halo-color'   => $_SYMBOL_SPORT_HALO_COLOR,
		),	
		"[sport='hillclimbing']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'hillclimbing',		
			'symbol-color' => $_SYMBOL_SPORT_COLOR,
			'text-color'   => $_SYMBOL_SPORT_COLOR,
			'symbol-halo'  => $_SYMBOL_SPORT_HALO_COLOR,
			'halo-color'   => $_SYMBOL_SPORT_HALO_COLOR,
		),		
		"[sport='multi']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'multi',		
			'symbol-color' => $_SYMBOL_SPORT_COLOR,
			'text-color'   => $_SYMBOL_SPORT_COLOR,
			'symbol-halo'  => $_SYMBOL_SPORT_HALO_COLOR,
			'halo-color'   => $_SYMBOL_SPORT_HALO_COLOR,
		),		
		"[sport='basketball']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'basketball',		
			'symbol-color' => $_SYMBOL_SPORT_COLOR,
			'text-color'   => $_SYMBOL_SPORT_COLOR,
			'symbol-halo'  => $_SYMBOL_SPORT_HALO_COLOR,
			'halo-color'   => $_SYMBOL_SPORT_HALO_COLOR,
		),	
		"[sport='golf']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_NORMAL,			
			'symbol-size'  => $_SYMBOl_SIZE_NORMAL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'golf',		
			'symbol-color' => $_SYMBOL_SPORT_COLOR,
			'text-color'   => $_SYMBOL_SPORT_COLOR,
			'symbol-halo'  => $_SYMBOL_SPORT_HALO_COLOR,
			'halo-color'   => $_SYMBOL_SPORT_HALO_COLOR,
		),
		"[sport='athletics']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'athletics',		
			'symbol-color' => $_SYMBOL_SPORT_COLOR,
			'text-color'   => $_SYMBOL_SPORT_COLOR,
			'symbol-halo'  => $_SYMBOL_SPORT_HALO_COLOR,
			'halo-color'   => $_SYMBOL_SPORT_HALO_COLOR,
		),
		"[sport='equestrian']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'horse_racing',		
			'symbol-color' => $_SYMBOL_SPORT_COLOR,
			'text-color'   => $_SYMBOL_SPORT_COLOR,
			'symbol-halo'  => $_SYMBOL_SPORT_HALO_COLOR,
			'halo-color'   => $_SYMBOL_SPORT_HALO_COLOR,
		),
		"[sport='bowls']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'bowls',		
			'symbol-color' => $_SYMBOL_SPORT_COLOR,
			'text-color'   => $_SYMBOL_SPORT_COLOR,
			'symbol-halo'  => $_SYMBOL_SPORT_HALO_COLOR,
			'halo-color'   => $_SYMBOL_SPORT_HALO_COLOR,
		),
		"[sport='skiing']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'skiing',		
			'symbol-color' => $_SYMBOL_SPORT_COLOR,
			'text-color'   => $_SYMBOL_SPORT_COLOR,
			'symbol-halo'  => $_SYMBOL_SPORT_HALO_COLOR,
			'halo-color'   => $_SYMBOL_SPORT_HALO_COLOR,
		),
		"[sport='volleyball']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'volleyball',		
			'symbol-color' => $_SYMBOL_SPORT_COLOR,
			'text-color'   => $_SYMBOL_SPORT_COLOR,
			'symbol-halo'  => $_SYMBOL_SPORT_HALO_COLOR,
			'halo-color'   => $_SYMBOL_SPORT_HALO_COLOR,
		),
		"[sport='shooting']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'shooting',		
			'symbol-color' => $_SYMBOL_SPORT_COLOR,
			'text-color'   => $_SYMBOL_SPORT_COLOR,
			'symbol-halo'  => $_SYMBOL_SPORT_HALO_COLOR,
			'halo-color'   => $_SYMBOL_SPORT_HALO_COLOR,
		),		
		"[sport='skateboard']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'skateboard',		
			'symbol-color' => $_SYMBOL_SPORT_COLOR,
			'text-color'   => $_SYMBOL_SPORT_COLOR,
			'symbol-halo'  => $_SYMBOL_SPORT_HALO_COLOR,
			'halo-color'   => $_SYMBOL_SPORT_HALO_COLOR,
		),
		"[sport='cricket']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'cricket',		
			'symbol-color' => $_SYMBOL_SPORT_COLOR,
			'text-color'   => $_SYMBOL_SPORT_COLOR,
			'symbol-halo'  => $_SYMBOL_SPORT_HALO_COLOR,
			'halo-color'   => $_SYMBOL_SPORT_HALO_COLOR,
		),		
		"[sport='beachvolleyball']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'volleyball',		
			'symbol-color' => $_SYMBOL_SPORT_COLOR,
			'text-color'   => $_SYMBOL_SPORT_COLOR,
			'symbol-halo'  => $_SYMBOL_SPORT_HALO_COLOR,
			'halo-color'   => $_SYMBOL_SPORT_HALO_COLOR,
		),
		"[sport='table_tennis']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'table_tennis',		
			'symbol-color' => $_SYMBOL_SPORT_COLOR,
			'text-color'   => $_SYMBOL_SPORT_COLOR,
			'symbol-halo'  => $_SYMBOL_SPORT_HALO_COLOR,
			'halo-color'   => $_SYMBOL_SPORT_HALO_COLOR,
		),
		"[sport='gymnastics']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'gymnastics',		
			'symbol-color' => $_SYMBOL_SPORT_COLOR,
			'text-color'   => $_SYMBOL_SPORT_COLOR,
			'symbol-halo'  => $_SYMBOL_SPORT_HALO_COLOR,
			'halo-color'   => $_SYMBOL_SPORT_HALO_COLOR,
		),
		"[sport='boules']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,			
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-file'  => 'bowls',		
			'symbol-color' => $_SYMBOL_SPORT_COLOR,
			'text-color'   => $_SYMBOL_SPORT_COLOR,
			'symbol-halo'  => $_SYMBOL_SPORT_HALO_COLOR,
			'halo-color'   => $_SYMBOL_SPORT_HALO_COLOR,
		),					
);
