<?php
require_once "inc/utils.php";
require_once "conf/common.conf.php";
require_once "conf/waters.conf.php";

$_SYMBOL_ATTRACTIVE_COLOR = array(12 => '#aa00aa');

$SYMBOL_DENSITY = array(11 => 5, 12 => 20,13 => 80, 14 => 300, 15 => 1000,16 => 20000);

$_SYMBOL_HALO_COLOR = array(12 => '#FFFAB3');


$_SYMBOL_TRANSPORT_COLOR = array(12 => '#453D4D');
$_SYMBOL_TRANSPORT_HALO_COLOR = array(12 => '#FFFFFF');
$_SYMBOL_TRANSPORT_HALO_OPACITY = array(12 => 0.5);

$_SYMBOL_HISTORIC_COLOR = array(12 => '#880000');
$_SYMBOL_HISTORIC_HALO_COLOR = $_SYMBOL_HALO_COLOR;

$_SYMBOL_AMENITY_COLOR = array(12 => '#3D4D4D');
$_SYMBOL_AMENITY_HALO_COLOR = array(12 => '#F2E4E4');

$_SYMBOL_NATURAL_COLOR = array(12 => '#448800');
$_SYMBOL_NATURAL_HALO_COLOR = $_SYMBOL_HALO_COLOR;

$_SYMBOl_SIZE_HUGE   = array(11=>17,14=>28,18=>37);
$_SYMBOl_SIZE_BIG    = array(11=>14,14=>21,18=>28);
$_SYMBOl_SIZE_NORMAL = array(11=>11,14=>16,18=>21);
$_SYMBOl_SIZE_SMALL  = array(11=> 9,14=>12,18=>16);
$_SYMBOl_SIZE_TINY   = array(11=> 7,14=> 9,18=>12);

$_SYMBOl_TEXT_SIZE_HUGE   = array(11=>11,14=>16,18=>21);
$_SYMBOl_TEXT_SIZE_BIG    = array(11=> 9,14=>11,18=>16);
$_SYMBOl_TEXT_SIZE_NORMAL = array(11=> 7,14=> 9,18=>11);
$_SYMBOl_TEXT_SIZE_SMALL  = array(11=> 5,14=> 7,18=> 9);
$_SYMBOl_TEXT_SIZE_TINY   = array(11=> 4,14=> 5,18=> 7);

$_SYMBOl_ZOOMS_HUGE    = array(11 => 4, 12 => 3, 13 => 3, 14 => 2, 15 => 2, 16 => 1, 17 => 1, 18 => 1);
$_SYMBOl_ZOOMS_HUGELOW = array(11 => 4, 12 => 4, 13 => 3, 14 => 3, 15 => 2, 16 => 2, 17 => 1, 18 => 1);
$_SYMBOl_ZOOMS_BIG     = array(         12 => 4, 13 => 3, 14 => 3, 15 => 2, 16 => 2, 17 => 1, 18 => 1);
$_SYMBOl_ZOOMS_NORMAL  = array(                  13 => 4, 14 => 3, 15 => 3, 16 => 2, 17 => 2, 18 => 1);
$_SYMBOl_ZOOMS_SMALL   = array(                           14 => 4, 15 => 3, 16 => 3, 17 => 2, 18 => 2);
$_SYMBOl_ZOOMS_TINY    = array(                                    15 => 4, 16 => 4, 17 => 3, 18 => 2);

/**
 * Zoom x symbol look maping
 */
$SYMBOL = array(	
	"[historic='castle'][castle_type='no'][ruins='no'],[historic='castle'][castle_type='stately'][ruins='no'],[historic='castle'][castle_type='schloss'][ruins='no'],[historic='castle'][castle_type='burg;schloss'][ruins='no']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_HUGE,
			'symbol-file'  => 'castle-stately',
			'symbol-size'  => $_SYMBOl_SIZE_HUGE,
			'text-size'    => $_SYMBOl_TEXT_SIZE_HUGE,
			'symbol-color' => $_SYMBOL_HISTORIC_COLOR,
			'text-color'   => $_SYMBOL_HISTORIC_COLOR,
			'symbol-halo'  => $_SYMBOL_HISTORIC_HALO_COLOR,
			'halo-color'   => $_SYMBOL_HISTORIC_HALO_COLOR,
		),	
	
	"[historic='castle'][castle_type='defensive'],[historic='castle'][castle_type='burg'],[historic='castle'][castle_type='fortress'],[historic='castle'][castle_type='festung']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_HUGE,
			'symbol-file'  => 'castle-defensive',
			'symbol-size'  => $_SYMBOl_SIZE_HUGE,
			'text-size'    => $_SYMBOl_TEXT_SIZE_HUGE,
			'symbol-color' => $_SYMBOL_HISTORIC_COLOR,
			'text-color'   => $_SYMBOL_HISTORIC_COLOR,
			'symbol-halo'  => $_SYMBOL_HISTORIC_HALO_COLOR,
			'halo-color'   => $_SYMBOL_HISTORIC_HALO_COLOR,
		),
	
		
	"[ruins!='no'][historic='castle'],[ruins='castle']" => array(			
			'zooms'        => $_SYMBOl_ZOOMS_HUGE,
			'symbol-file'  => 'ruins',
			'symbol-size'  => $_SYMBOl_SIZE_BIG,
			'text-size'    => $_SYMBOl_TEXT_SIZE_BIG,
			'symbol-color' => $_SYMBOL_HISTORIC_COLOR,
			'text-color'   => $_SYMBOL_HISTORIC_COLOR,
			'symbol-halo'  => $_SYMBOL_HISTORIC_HALO_COLOR,
			'halo-color'   => $_SYMBOL_HISTORIC_HALO_COLOR,
		),	
	
	"[building='church'],[amenity='place_of_worship'][historic!='monastery'][historic!='wayside_shrine'][historic!='wayside_cross'][building!='chapel'][\"place_of_worship:type\"!='chapel'][place_of_worship!='chapel'][\"place_of_worship:type\"!='monastery'][place_of_worship!='monastery']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_HUGE,
			'symbol-file'  => 'church',
			'symbol-size'  => $_SYMBOl_SIZE_NORMAL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_NORMAL,
			'symbol-color' => $_SYMBOL_HISTORIC_COLOR,
			'text-color'   => $_SYMBOL_HISTORIC_COLOR,
			'symbol-halo'  => $_SYMBOL_HISTORIC_HALO_COLOR,
			'halo-color'   => $_SYMBOL_HISTORIC_HALO_COLOR,
		),	
		
	"[building='chapel'],[\"place_of_worship:type\"='chapel'],[place_of_worship='chapel']"=> array(			
			'zooms'        => $_SYMBOl_ZOOMS_BIG,
			'symbol-file'  => 'chapel',
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_SMALL,
			'symbol-color' => $_SYMBOL_HISTORIC_COLOR,
			'text-color'   => $_SYMBOL_HISTORIC_COLOR,
			'symbol-halo'  => $_SYMBOL_HISTORIC_HALO_COLOR,
			'halo-color'   => $_SYMBOL_HISTORIC_HALO_COLOR,
		),	
	"[historic='monastery'],[\"place_of_worship:type\"='monastery'],[place_of_worship='monastery']"=> array(			
			'zooms'        => $_SYMBOl_ZOOMS_HUGE,
			'symbol-file'  => 'monastery',
			'symbol-size'  => $_SYMBOl_SIZE_BIG,
			'text-size'    => $_SYMBOl_TEXT_SIZE_BIG,
			'symbol-color' => $_SYMBOL_HISTORIC_COLOR,
			'text-color'   => $_SYMBOL_HISTORIC_COLOR,
			'symbol-halo'  => $_SYMBOL_HISTORIC_HALO_COLOR,
			'halo-color'   => $_SYMBOL_HISTORIC_HALO_COLOR,
		),
	
	"[historic='monument']" => array(			
			'zooms'        => $_SYMBOl_ZOOMS_BIG,
			'symbol-file'  => 'monument',
			'symbol-size'  => $_SYMBOl_SIZE_NORMAL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_NORMAL,
			'symbol-color' => $_SYMBOL_HISTORIC_COLOR,
			'text-color'   => $_SYMBOL_HISTORIC_COLOR,
			'symbol-halo'  => $_SYMBOL_HISTORIC_HALO_COLOR,
			'halo-color'   => $_SYMBOL_HISTORIC_HALO_COLOR,
		),	
	"[historic='memorial']" => array(			
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,
			'symbol-file'  => 'memorial',
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-color' => $_SYMBOL_HISTORIC_COLOR,
			'text-color'   => $_SYMBOL_HISTORIC_COLOR,
			'symbol-halo'  => $_SYMBOL_HISTORIC_HALO_COLOR,
			'halo-color'   => $_SYMBOL_HISTORIC_HALO_COLOR,
		),
	"[historic='wayside_cross'],[amenity='place_of_worship'][historic='no'][building='no']" => array(			
			'zooms'        => $_SYMBOl_ZOOMS_NORMAL,
			'symbol-file'  => 'waysidecross',
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-color' => $_SYMBOL_HISTORIC_COLOR,
			'text-color'   => $_SYMBOL_HISTORIC_COLOR,
			'symbol-halo'  => $_SYMBOL_HISTORIC_HALO_COLOR,
			'halo-color'   => $_SYMBOL_HISTORIC_HALO_COLOR,
		),
	"[historic='wayside_shrine']" => array(			
			'zooms'        => $_SYMBOl_ZOOMS_NORMAL,
			'symbol-file'  => 'waysideshrine',
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-color' => $_SYMBOL_HISTORIC_COLOR,
			'text-color'   => $_SYMBOL_HISTORIC_COLOR,
			'symbol-halo'  => $_SYMBOL_HISTORIC_HALO_COLOR,
			'halo-color'   => $_SYMBOL_HISTORIC_HALO_COLOR,
		),
		
	"[man_made='tower'][\"tower:type\"='observation'],[man_made='tower'][tourism='attraction']" => array(			
			'zooms'        => $_SYMBOl_ZOOMS_BIG,
			'symbol-file'  => 'tower-observation',
			'symbol-size'  => $_SYMBOl_SIZE_BIG,
			'text-size'    => $_SYMBOl_TEXT_SIZE_BIG,
			'symbol-color' => $_SYMBOL_HISTORIC_COLOR,
			'text-color'   => $_SYMBOL_HISTORIC_COLOR,
			'symbol-halo'  => $_SYMBOL_HISTORIC_HALO_COLOR,
			'halo-color'   => $_SYMBOL_HISTORIC_HALO_COLOR,
		),
	
	"[man_made='tower'][\"tower:type\"='communication']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_NORMAL,
			'symbol-file'  => 'tower-comunication',
			'symbol-size'  => $_SYMBOl_SIZE_NORMAL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_NORMAL,
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),	
	"[man_made='water_tower']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_NORMAL,
			'symbol-file'  => 'tower-water',
			'symbol-size'  => $_SYMBOl_SIZE_NORMAL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_NORMAL,
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
	"[tourism='viewpoint']" => array(			
			'zooms'        => $_SYMBOl_ZOOMS_NORMAL,
			'symbol-file'  => 'viewpoint',
			'symbol-size'  => $_SYMBOl_SIZE_NORMAL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_NORMAL,
			'symbol-color' => $_SYMBOL_HISTORIC_COLOR,
			'text-color'   => $_SYMBOL_HISTORIC_COLOR,
			'symbol-halo'  => $_SYMBOL_HISTORIC_HALO_COLOR,
			'halo-color'   => $_SYMBOL_HISTORIC_HALO_COLOR,
		),	
	"[tourism='museum']" => array(			
			'zooms'        => $_SYMBOl_ZOOMS_BIG,
			'symbol-file'  => 'museum',
			'symbol-size'  => $_SYMBOl_SIZE_NORMAL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_NORMAL,
			'symbol-color' => $_SYMBOL_HISTORIC_COLOR,
			'text-color'   => $_SYMBOL_HISTORIC_COLOR,
			'symbol-halo'  => $_SYMBOL_HISTORIC_HALO_COLOR,
			'halo-color'   => $_SYMBOL_HISTORIC_HALO_COLOR,
		),	
		
	"[tourism='zoo']" => array(			
			'zooms'        => $_SYMBOl_ZOOMS_BIG,
			'symbol-file'  => 'zoo',
			'symbol-size'  => $_SYMBOl_SIZE_BIG,
			'text-size'    => $_SYMBOl_TEXT_SIZE_BIG,
			'symbol-color' => $_SYMBOL_HISTORIC_COLOR,
			'text-color'   => $_SYMBOL_HISTORIC_COLOR,
			'symbol-halo'  => $_SYMBOL_HISTORIC_HALO_COLOR,
			'halo-color'   => $_SYMBOL_HISTORIC_HALO_COLOR,
		),	
		
	"[tourism='camp_site']" => array(			
			'zooms'        => $_SYMBOl_ZOOMS_HUGELOW,
			'symbol-file'  => 'camp',
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_SMALL,
			'symbol-color' => $_SYMBOL_HISTORIC_COLOR,
			'text-color'   => $_SYMBOL_HISTORIC_COLOR,
			'symbol-halo'  => $_SYMBOL_HISTORIC_HALO_COLOR,
			'halo-color'   => $_SYMBOL_HISTORIC_HALO_COLOR,		
		),	
	"[tourism='information'][information='guidepost']" => array(			
			'zooms'        => $_SYMBOl_ZOOMS_BIG,
			'symbol-file'  => 'information-guidepost',
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_SMALL,
			'symbol-color' => $_SYMBOL_HISTORIC_COLOR,
			'text-color'   => $_SYMBOL_HISTORIC_COLOR,
			'symbol-halo'  => $_SYMBOL_HISTORIC_HALO_COLOR,
			'halo-color'   => $_SYMBOL_HISTORIC_HALO_COLOR,		
		),	
	"[tourism='information'][information='board']" => array(			
			'zooms'        => $_SYMBOl_ZOOMS_NORMAL,
			'symbol-file'  => 'information-board',
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_SMALL,
			'symbol-color' => $_SYMBOL_HISTORIC_COLOR,
			'text-color'   => $_SYMBOL_HISTORIC_COLOR,
			'symbol-halo'  => $_SYMBOL_HISTORIC_HALO_COLOR,
			'halo-color'   => $_SYMBOL_HISTORIC_HALO_COLOR,	
		),	
	"[tourism='information'][information='map']" => array(			
			'zooms'        => $_SYMBOl_ZOOMS_NORMAL,
			'symbol-file'  => 'information-map',
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_SMALL,
			'symbol-color' => $_SYMBOL_HISTORIC_COLOR,
			'text-color'   => $_SYMBOL_HISTORIC_COLOR,
			'symbol-halo'  => $_SYMBOL_HISTORIC_HALO_COLOR,
			'halo-color'   => $_SYMBOL_HISTORIC_HALO_COLOR,	
		),	
	"[tourism='information'][information='office']" => array(			
			'zooms'        => $_SYMBOl_ZOOMS_NORMAL,
			'symbol-file'  => 'information-office',
			'symbol-size'  => $_SYMBOl_SIZE_NORMAL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_NORMAL,
			'symbol-color' => $_SYMBOL_HISTORIC_COLOR,
			'text-color'   => $_SYMBOL_HISTORIC_COLOR,
			'symbol-halo'  => $_SYMBOL_HISTORIC_HALO_COLOR,
			'halo-color'   => $_SYMBOL_HISTORIC_HALO_COLOR,	
		),	
	"[tourism='artwork']" => array(			
			'zooms'        => $_SYMBOl_ZOOMS_NORMAL,
			'symbol-file'  => 'artwork-statue',
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_SMALL,
			'symbol-color' => $_SYMBOL_HISTORIC_COLOR,
			'text-color'   => $_SYMBOL_HISTORIC_COLOR,
			'symbol-halo'  => $_SYMBOL_HISTORIC_HALO_COLOR,
			'halo-color'   => $_SYMBOL_HISTORIC_HALO_COLOR,	
		),
	"[amenity='atm']" => array(			
			'zooms'        => $_SYMBOl_ZOOMS_TINY,
			'symbol-file'  => 'atm',
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
	"[amenity='bank']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,
			'symbol-file'  => 'bank',
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_SMALL,
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
	"[amenity='bench']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_TINY,
			'symbol-file'  => 'bench',
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
	"[natural='cave_entrance']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_BIG,
			'symbol-file'  => 'cave',
			'symbol-size'  => $_SYMBOl_SIZE_BIG,
			'text-size'    => $_SYMBOl_TEXT_SIZE_BIG,
			'symbol-color' => $_SYMBOL_NATURAL_COLOR,
			'text-color'   => $_SYMBOL_NATURAL_COLOR,
			'symbol-halo'  => $_SYMBOL_NATURAL_HALO_COLOR,
			'halo-color'   => $_SYMBOL_NATURAL_HALO_COLOR,
		),	
	"[amenity='doctors'],[amenity='dentist']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,
			'symbol-file'  => 'doctors',
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
	"[amenity='hospital']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,
			'symbol-file'  => 'hospital',
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_SMALL,
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
	"[amenity='clinic']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,
			'symbol-file'  => 'hospital',
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
	"[amenity='drinking_water']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_TINY,
			'symbol-file'  => 'drinking-water',
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-color' => $_SYMBOL_HISTORIC_COLOR,
			'text-color'   => $_SYMBOL_HISTORIC_COLOR,
			'symbol-halo'  => $_SYMBOL_HISTORIC_HALO_COLOR,
			'halo-color'   => $_SYMBOL_HISTORIC_HALO_COLOR,	
		),
	"[amenity='fuel']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_HUGELOW,
			'symbol-file'  => 'fuel',
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_SMALL,
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
	"[tourism='guest_house'],[tourism='hostel'],[tourism='motel'],[tourism='hut'],[tourism='alpine_hut']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_NORMAL,
			'symbol-file'  => 'guest-house',
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_SMALL,
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
	"[tourism='hotel']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_NORMAL,
			'symbol-file'  => 'hotel',
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_SMALL,
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
		
	"[man_made='hunting_stand'],[amenity='hunting_stand']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,
			'symbol-file'  => 'hunting-stand',
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),	
	"[amenity='parking']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_BIG,
			'symbol-file'  => 'parking',
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
	"[amenity='pharmacy']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_TINY,
			'symbol-file'  => 'pharmacy',
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
	"[tourism='picnic_site'],[leisure='picnic_table']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,
			'symbol-file'  => 'picnic',
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
	"[amenity='post_box']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_TINY,
			'symbol-file'  => 'postbox',
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
	"[amenity='post_office']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,
			'symbol-file'  => 'postoffice',
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_SMALL,
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
	"[amenity='pub'],[amenity='bar']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,
			'symbol-file'  => 'pub',
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_SMALL,
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
	"[amenity='restaurant']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,
			'symbol-file'  => 'restaurant',
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_SMALL,
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
	"[amenity='shelter']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_SMALL,
			'symbol-file'  => 'shelter',
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-color' => $_SYMBOL_AMENITY_COLOR,
			'text-color'   => $_SYMBOL_AMENITY_COLOR,
			'symbol-halo'  => $_SYMBOL_AMENITY_HALO_COLOR,
			'halo-color'   => $_SYMBOL_AMENITY_HALO_COLOR,
		),
	"[natural='spring']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_NORMAL,
			'symbol-file'  => 'spring',
			'symbol-size'  => $_SYMBOl_SIZE_TINY,
			'text-size'    => $_SYMBOl_TEXT_SIZE_TINY,
			'symbol-color' => $_SYMBOL_NATURAL_COLOR,
			'text-color'   => $_SYMBOL_NATURAL_COLOR,
			'symbol-halo'  => $_SYMBOL_NATURAL_HALO_COLOR,
			'halo-color'   => $_SYMBOL_NATURAL_HALO_COLOR,
		),
	"[amenity='theatre']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_BIG,
			'symbol-file'  => 'theatre',
			'symbol-size'  => $_SYMBOl_SIZE_NORMAL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_NORMAL,
			'symbol-color' => $_SYMBOL_HISTORIC_COLOR,
			'text-color'   => $_SYMBOL_HISTORIC_COLOR,
			'symbol-halo'  => $_SYMBOL_HISTORIC_HALO_COLOR,
			'halo-color'   => $_SYMBOL_HISTORIC_HALO_COLOR,
		),	
	"[man_made='watermill']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_BIG,
			'symbol-file'  => 'watermill',
			'symbol-size'  => $_SYMBOl_SIZE_NORMAL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_NORMAL,
			'symbol-color' => $_SYMBOL_HISTORIC_COLOR,
			'text-color'   => $_SYMBOL_HISTORIC_COLOR,
			'symbol-halo'  => $_SYMBOL_HISTORIC_HALO_COLOR,
			'halo-color'   => $_SYMBOL_HISTORIC_HALO_COLOR,
		),
	"[man_made='water_well']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_BIG,
			'symbol-file'  => 'waterwell',
			'symbol-size'  => $_SYMBOl_SIZE_NORMAL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_NORMAL,
			'symbol-color' => $_SYMBOL_HISTORIC_COLOR,
			'text-color'   => $_SYMBOL_HISTORIC_COLOR,
			'symbol-halo'  => $_SYMBOL_HISTORIC_HALO_COLOR,
			'halo-color'   => $_SYMBOL_HISTORIC_HALO_COLOR,
		),
	"[man_made='windmill']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_BIG,
			'symbol-file'  => 'windmill',
			'symbol-size'  => $_SYMBOl_SIZE_NORMAL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_NORMAL,
			'symbol-color' => $_SYMBOL_HISTORIC_COLOR,
			'text-color'   => $_SYMBOL_HISTORIC_COLOR,
			'symbol-halo'  => $_SYMBOL_HISTORIC_HALO_COLOR,
			'halo-color'   => $_SYMBOL_HISTORIC_HALO_COLOR,
		),	
	"[amenity='fountain']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_NORMAL,
			'symbol-file'  => 'fontain',
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_SMALL,
			'symbol-color' => $_SYMBOL_HISTORIC_COLOR,
			'text-color'   => $_SYMBOL_HISTORIC_COLOR,
			'symbol-halo'  => $_SYMBOL_HISTORIC_HALO_COLOR,
			'halo-color'   => $_SYMBOL_HISTORIC_HALO_COLOR,	
		),	
	"[railway='tram_stop']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_NORMAL,			
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_SMALL,
			'symbol-file'  => 'tram_stop',		
			'symbol-color' => $_SYMBOL_TRANSPORT_COLOR,
			'text-color'   => $_SYMBOL_TRANSPORT_COLOR,
			'symbol-halo'  => $_SYMBOL_TRANSPORT_HALO_COLOR,
			'halo-color'   => $_SYMBOL_TRANSPORT_HALO_COLOR,
			'halo-opacity' => $_SYMBOL_TRANSPORT_HALO_OPACITY,
		),
	"[highway='bus_stop']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_BIG,			
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_SMALL,
			'symbol-file'  => 'bus_stop',		
			'symbol-color' => $_SYMBOL_TRANSPORT_COLOR,
			'text-color'   => $_SYMBOL_TRANSPORT_COLOR,
			'symbol-halo'  => $_SYMBOL_TRANSPORT_HALO_COLOR,
			'halo-color'   => $_SYMBOL_TRANSPORT_HALO_COLOR,
			'halo-opacity' => $_SYMBOL_TRANSPORT_HALO_OPACITY,
		),
	"[aeroway='aerodrome']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_HUGE,			
			'symbol-size'  => $_SYMBOl_SIZE_HUGE,
			'text-size'    => $_SYMBOl_TEXT_SIZE_HUGE,
			'symbol-file'  => 'aerodrom',		
			'symbol-color' => $_SYMBOL_TRANSPORT_COLOR,
			'text-color'   => $_SYMBOL_TRANSPORT_COLOR,
			'symbol-halo'  => $_SYMBOL_TRANSPORT_HALO_COLOR,
			'halo-color'   => $_SYMBOL_TRANSPORT_HALO_COLOR,	
			'halo-opacity' => $_SYMBOL_TRANSPORT_HALO_OPACITY,
		),
	"[railway='subway_entrance']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_NORMAL,			
			'symbol-size'  => $_SYMBOl_SIZE_SMALL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_SMALL,
			'symbol-file'  => 'subway_entrance',		
			'symbol-color' => $_SYMBOL_TRANSPORT_COLOR,
			'text-color'   => $_SYMBOL_TRANSPORT_COLOR,
			'symbol-halo'  => $_SYMBOL_TRANSPORT_HALO_COLOR,
			'halo-color'   => $_SYMBOL_TRANSPORT_HALO_COLOR,	
			'halo-opacity' => $_SYMBOL_TRANSPORT_HALO_OPACITY,
		),
	"[railway='halt']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_HUGE,			
			'symbol-size'  => $_SYMBOl_SIZE_NORMAL,
			'text-size'    => $_SYMBOl_TEXT_SIZE_NORMAL,
			'symbol-file'  => 'station',		
			'symbol-color' => $_SYMBOL_TRANSPORT_COLOR,
			'text-color'   => $_SYMBOL_TRANSPORT_COLOR,
			'symbol-halo'  => $_SYMBOL_TRANSPORT_HALO_COLOR,
			'halo-color'   => $_SYMBOL_TRANSPORT_HALO_COLOR,
			'halo-opacity' => $_SYMBOL_TRANSPORT_HALO_OPACITY,
		),
	"[railway='station']" => array(
			'zooms'        => $_SYMBOl_ZOOMS_HUGE,			
			'symbol-size'  => $_SYMBOl_SIZE_BIG,
			'text-size'    => $_SYMBOl_TEXT_SIZE_BIG,
			'symbol-file'  => 'station',		
			'symbol-color' => $_SYMBOL_TRANSPORT_COLOR,
			'text-color'   => $_SYMBOL_TRANSPORT_COLOR,
			'symbol-halo'  => $_SYMBOL_TRANSPORT_HALO_COLOR,
			'halo-color'   => $_SYMBOL_TRANSPORT_HALO_COLOR,
			'halo-opacity' => $_SYMBOL_TRANSPORT_HALO_OPACITY,
		),	
	
);
